"""Initial schema with auth, users, and clinics

Revision ID: 00d040ad36b4
Revises: 
Create Date: 2026-01-17 16:48:52.194426

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '00d040ad36b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
